# <p align="center"> Filter Fragalysis </P>

## <p align="center"> Select Piperidine Series and active Site </p>

<details open>
<summary> <font size = "6"> <ins> Open Questions </ins> </font> </summary>

- How is the "active site" label in the metadata defined? Is the region of the catalytic triad? Or the area that the activitiy assay peptide probe binds to in the protein? Or is it the area that a sequence of fragments bind to involving the catalytic triad? Or is it defined in another different way?

</details>

## Analysing Metadata - <font size = "5"> `metadata.csv`</font>

In [1]:
from pathlib import Path
import sys
sys.path.insert( 0, str(Path("../../../..").resolve().absolute()) )

import pandas as pd

### Look at Table

In [2]:
frag_csv_path = Path( "../../../../data/ev2a/fragalysis/01-concatDir/metadata.csv" ).resolve()
if  frag_csv_path.exists(): print( "All Fragalysis data path:", frag_csv_path )
else: raise FileNotFoundError( f"Fragalysis data file not found: {frag_csv_path}" ) 
df = pd.read_csv( frag_csv_path )
display( df.head() )

All Fragalysis data path: /dls/data2temp01/alex/data/ev2a/fragalysis/01-concatDir/metadata.csv

,Code,Long code,Experiment code,Compound code,Smiles,Centroid res,Downloaded,ConformerSites upload name,CanonSites upload name,CrystalformSites upload name,...,[Other] upload_5 2025-04-10,[Other] upload_1 2024-12-06,[Other] upload_1 2025-02-12,[Other] upload_2 2025-02-28,[Other] upload_6 2025-09-15,Main status,GOOD count,MEDIOCRE count,BAD count,RefinementResolution
0,A0450a,A71EV2A-x0450_A_201_v1,A71EV2A-x0450,Z100642432,CN(C)C(=O)c1ccc(F)cc1Br,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F2b - A71EV2A-x0450/A/201/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.61
1,A0451a,A71EV2A-x0451_A_201_v1,A71EV2A-x0451,Z100643660,CNC(=O)c1cn(C)c2ccccc12,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F1a - A71EV2A-x0375/A/201/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.50
2,A0469a,A71EV2A-x0469_A_147_v1,A71EV2A-x0469,Z104924088,CC(C)N1CCN(c2ncccn2)CC1,A71EV2A-x0525/A/90/A_v1,True,4b - A71EV2A-x0469/A/147,4 - A71EV2A-x0525/A/246/1,F1z - A71EV2A-x0525/A/246/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.05
3,A0473a,A71EV2A-x0473_A_147_v1,A71EV2A-x0473,Z1082839290,O=S(=O)(NC1CCCC1)C1CCOCC1,A71EV2A-x0911/A/133/A_v1,True,1b - A71EV2A-x0911/A/147,1 - A71EV2A-x0911/A/147/1,F1a - A71EV2A-x0375/A/201/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.06
4,A0486a,A71EV2A-x0486_A_147_v1,A71EV2A-x0486,Z1148165337,CN(C)C(=O)Cn1ncc2ccccc21,A71EV2A-x0486/A/143/A_v1,True,6a - A71EV2A-x0486/A/147,6 - A71EV2A-x0486/A/147/1,F1ac - A71EV2A-x0486/A/147/1,...,False,True,True,False,False,NaN,NaN,NaN,NaN,1.24

#### List All Table Columns

In [3]:
window_size = 2
for idx in range( ( len( df.columns.values) // 2 )+ 1):
    print( df.columns.values[ idx*window_size : (idx+1)*window_size ], "\n" )

['Code' 'Long code']

['Experiment code' 'Compound code']

['Smiles' 'Centroid res']

['Downloaded' 'ConformerSites upload name']

['CanonSites upload name' 'CrystalformSites upload name']

['Quatassemblies upload name' 'Crystalforms upload name']

['ConformerSites short tag' 'CanonSites short tag']

['CrystalformSites short tag' 'Quatassemblies short tag']

['Crystalforms short tag' 'ConformerSites alias']

['CanonSites alias' 'CrystalformSites alias']

['Quatassemblies alias' 'Crystalforms alias']

['Pose' '[Other] upload_4 2025-04-02']

['[Other] Lactam Series' '[Other] cyclopropane']

['[Other] fff_i1_design' '[Other] New']

['[Other] P2 Wave 1' '[Other] Active site fragment']

['[Other] upload_6_2025-02-13' '[Other] S2 site']

['[Other] Fragment Screen' '[Other] Bogyo covalents']

['[Other] Covalent' '[Series] Indazole series']

['[Other] upload_3 2024-12-19' '[Other] upload_4 2025-01-06']

['[Other] upload_5 2025-02-03' '[Other] upload_061224']

['[Other] S3 site' '[Other] S4 site']

['[Other] S5 site' '[Other] Sun-roof open']

['[Other] upload_2 2024-12-12' '[Other] S1 site']

["[Other] S1' site" '[Other] upload_3 2025-03-06']

['[Series] Piperidine series' '[Other] P3 compound design']

['[Other] upload_5 2025-04-10' '[Other] upload_1 2024-12-06']

['[Other] upload_1 2025-02-12' '[Other] upload_2 2025-02-28']

['[Other] upload_6 2025-09-15' 'Main status']

['GOOD count' 'MEDIOCRE count']

['BAD count' 'RefinementResolution']

[]

<details open>
<summary>Column Labels Notes:</summary>



XCA-asssigned sites/tags

&emsp; These tags are auto-generated with names and colours (e.g. `2 - c0692/D/304/1`)

- Conformer Site = "The set of **binders** whose structural context can be aligned, even indirectly, with a good RMSD"

    <details>
    <summary> My Interpretation: </summary>
    


    </details>


- CanonSites = Canonical Site

    "main XCA-assigned site"

    "The union of **residues** present in overlapping conformer sites"


- Crystal Form Site =  Crystal Structure

    "The subset of conformer sites which share a crystalform"

- Quaternary Assembly = Biological Assembly

Manually-assigned tags

- Main Status = "experimental / model quality [...] indicated using the traffic light system"

- Other -- new tag -- = "For additional annotation of structures "

    [Fragalysis Reference Document](https://fragalysis.readthedocs.io/en/latest/tags.html)

    [XCA Reference Document](https://xchem-align.readthedocs.io/en/latest/ALGORITHM-GUIDE.html)

    The primary challenge that XChemAlign deals with is the identification of which subset of residues are meaningful to perform alignments [...] around said subset of residues

    Goal: generating the biologically relevant binding site / generate the conformer site 

    - The first step: identify which compounds bind with a similar structural context

        - In crystallography:  structural context = Biological Assembly (biological binding context) + Crystallographic Artefacts
    
    - the next step: identify which **compounds** have **protein contexts** which can be aligned to one another well

</details>

#### Identify Columns of Interest

<details open>
<summary> <ins>Columns of Interest </ins>  </summary>
    
- **Identifiers of Interest**

    - `'Code'`
        
        E.g. -> A0473a

        Format: A{dataset Number}{Subset Number}
    
    - `'Experiment Code' `

        E.g. -> A71EV2A-x0450	

        Format: datasetID = {referenceID}-{datasetID}
    
    - `'Compound Code'`

        E.g. -> Z100642432 | NCL-00024665 | ASAP-0016618-001 | nan
    
    - `'Smiles'`

        E.g. -> 

- **Chemical Series of Interest**

    - `"[Other] Fragment Screen"`

        It seems to refer to data about the initial fragment screen performed.

    - `"[Other] Active site fragment"`

        It seems to refer to the compounds that bind to the active site. 

        Q. How is the active site defined?

    -  `"[Series] Piperidine series"`

- **Protein Sites of Interst**

    - Active Site:
    
        -  "[Other] S1 site" | "[Other] S2 site" |"[Other] S3 site" |"[Other] S4 site"|"[Other] S5 site" |"[Other] S1' site"
    
    - Roof

        - '[Other] Sun-roof open'


    

</details>

### <ins> Column Labels Individual Analysis </ins>

#### Analyse `'Code'` Column Regex Content

In [ ]:
import re
lst_regex_pattern = ["^A[0-9]*[a-z]$" ] # E.g. A0450a
lst_regex_obj = [ re.compile(pattern) for pattern in lst_regex_pattern]

regex_match_dict = { "match": [], "mismatch": []}


for value in df['Code'].values:
    matched = False
    for regex_obj in lst_regex_obj: 
        if regex_obj.search( value): 
            regex_match_dict["match"].append( value )
            matched = True
    if not matched: regex_match_dict["mismatch"].append(value)

print(regex_match_dict["mismatch"])
if regex_match_dict["mismatch"].__len__() == 0:
    print( "\'Code\' Label is composed of the following regex:\n\t{}" \
    "".format(lst_regex_pattern))

[]
'Code' Label is composed of the following regex:
	['^A[0-9]*[a-z]$']

#### Analyse `'Experiment code'` Column Regex Content

In [ ]:
import re
lst_regex_pattern = ["^A71EV2A-x[0-9]*$" ] # E.g. A71EV2A-x0450	
lst_regex_obj = [ re.compile(pattern) for pattern in lst_regex_pattern]

regex_match_dict = { "match": [], "mismatch": []}


for value in df['Experiment code'].values:
    matched = False
    for regex_obj in lst_regex_obj: 
        if regex_obj.search( value): 
            regex_match_dict["match"].append( value )
            matched = True
    if not matched: regex_match_dict["mismatch"].append(value)

print(regex_match_dict["mismatch"])
if regex_match_dict["mismatch"].__len__() == 0:
    print( "\'Experiment code\' Label is composed of the following regex:\n\t{}" \
    "".format(lst_regex_pattern))

[]
'Experiment code' Label is composed of the following regex:
	['^A71EV2A-x[0-9]*$']

#### Analyse `'Compound code'` Column Regex Content

In [ ]:
import re
lst_regex_pattern = [ "^Z[0-9]*", "^NCL-[0-9]*", "^ASAP-[0-9]*-[0-9]*$", "^nan$"] # E.g. Z100642432 | NCL-00024665 | ASAP-0016618-001 | nan
lst_regex_obj = [ re.compile(pattern) for pattern in lst_regex_pattern]

regex_match_dict = { "match": [], "mismatch": []}


for value in df["Compound code"].values:
    matched = False
    for regex_obj in lst_regex_obj: 
        if regex_obj.search( str(value)):                                       # Note that some are not in string format
            regex_match_dict["match"].append( value )
            matched = True
    if not matched: regex_match_dict["mismatch"].append(value)

print(regex_match_dict["mismatch"])
if regex_match_dict["mismatch"].__len__() == 0:
    print( "\'Compound code\' Label is composed of the following regex:\n\t{}" \
    "".format(lst_regex_pattern))

[]
'Compound code' Label is composed of the following regex:
	['^Z[0-9]*', '^NCL-[0-9]*', '^ASAP-[0-9]*-[0-9]*$', '^nan$']

#### Analyse `'Main Status'` Column Regex Content

In [40]:
import re
lst_regex_pattern = [ "^nan$", "^BAD$"] # E.g. Z100642432 | NCL-00024665 | ASAP-0016618-001 | nan
lst_regex_obj = [ re.compile(pattern) for pattern in lst_regex_pattern]

regex_match_dict = { "match": [], "mismatch": []}


for value in df["Main status"].values:
    matched = False
    for regex_obj in lst_regex_obj: 
        if regex_obj.search( str(value)):                                       # Note that some are not in string format
            regex_match_dict["match"].append( value )
            matched = True
    if not matched: regex_match_dict["mismatch"].append(value)

print(regex_match_dict["mismatch"])
if regex_match_dict["mismatch"].__len__() == 0:
    print( "\'Main status\' Label is composed of the following regex:\n\t{}" \
    "".format(lst_regex_pattern))

[]
'Main status' Label is composed of the following regex:
	['^nan$', '^BAD$']

#### Analyse Identified Columns with Labels of Interest

In [36]:
labels_of_interest = ["[Other] Active site fragment", "[Series] Piperidine series", "[Other] Fragment Screen"]
display( df[labels_of_interest].head() )
labels_content = { label: set() for label in labels_of_interest}
for label, content in labels_content.items():
    for df_value in df[ label].values:
        content.add( type(df_value) )
print( "Content For Each Label of Interest: ")
for label, content in labels_content.items():
    print("Label:   {}\t-\t Content: {}".format(label, content))

,[Other] Active site fragment,[Series] Piperidine series,[Other] Fragment Screen
0,True,False,True
1,True,False,True
2,False,False,True
3,True,False,True
4,False,False,True

Content For Each Label of Interest:
Label:   [Other] Active site fragment	-	 Content: {<class 'numpy.bool'>}
Label:   [Series] Piperidine series	-	 Content: {<class 'numpy.bool'>}
Label:   [Other] Fragment Screen	-	 Content: {<class 'numpy.bool'>}

#### Analyse XCA Auto-generated `ConformerSites upload name` Labels

In [66]:
ordered_unique_labels = set()

for value in df["ConformerSites upload name"].values:
    ordered_unique_labels.add(value)
ordered_unique_labels = sorted( sorted(list( ordered_unique_labels)), key = lambda x: int( re.search( "^[0-9]*", x).group() )  )
window = 2
for i in range( len( ordered_unique_labels) // window ):
    print( ordered_unique_labels[i*window:(i+1)*window])

['1a - A71EV2A-x0739/A/147', '1b - A71EV2A-x0911/A/147']
['2a - A71EV2A-x3977/A/202', '3a - A71EV2A-x0541/A/147']
['4a - A71EV2A-x0359/A/147', '4b - A71EV2A-x0469/A/147']
['4c - A71EV2A-x0525/A/246', '4d - A71EV2A-x0922/A/147']
['5a - A71EV2A-x3181/A/202', '6a - A71EV2A-x0486/A/147']
['7a - A71EV2A-x0202/A/201', '7b - A71EV2A-x0488/A/147']
['7c - A71EV2A-x1081/A/147', '7d - A71EV2A-x1084/A/147']
['8a - A71EV2A-x0517/A/147', '9a - A71EV2A-x0432/A/147']
['10a - A71EV2A-x0900/A/147', '10b - A71EV2A-x1128/A/147']
['11a - A71EV2A-x0379/A/147', '12a - A71EV2A-x0396/A/147']
['13a - A71EV2A-x0412/A/147', '14a - A71EV2A-x0554/A/147']
['15a - A71EV2A-x1068/A/246', '16a - A71EV2A-x1068/A/302']
['17a - A71EV2A-x1081/A/201', '18a - A71EV2A-x7475/A/201']

In [102]:
count = 0

In [106]:
conf_of_int = ['7a - A71EV2A-x0202/A/201', '7b - A71EV2A-x0488/A/147','7c - A71EV2A-x1081/A/147', '7d - A71EV2A-x1084/A/147'] # ['1a - A71EV2A-x0739/A/147', '1b - A71EV2A-x0911/A/147'] #  

print( df["Code"][ (df["ConformerSites upload name"] == conf_of_int[count]) ].to_list() )
count +=1

['A1084a']

#### Analyse XCA Auto-generated `CanonSites` Labels

In [93]:
print( "\nUploaded Name")
ordered_unique_labels = set()
for value in df["CanonSites upload name"].values:
    ordered_unique_labels.add(value)
ordered_unique_labels = sorted( sorted(list( ordered_unique_labels)), key = lambda x: int( re.search( "^[0-9]*", x).group() )  )
window = 2
for i in range( len( ordered_unique_labels) // window ):
    print( ordered_unique_labels[i*window:(i+1)*window])

print( "\nShort Tag")
ordered_unique_labels = set()
for value in df["CanonSites short tag"].values:
    ordered_unique_labels.add(value)
ordered_unique_labels = sorted( sorted(list( ordered_unique_labels)), key = lambda x: int( re.search( "^[0-9]*", x).group() )  )
window = 2
for i in range( len( ordered_unique_labels) // window ):
    print( ordered_unique_labels[i*window:(i+1)*window])

print("\n Alias")
ordered_unique_labels = set()
for value in df["CanonSites alias"].values:
    ordered_unique_labels.add(value)
ordered_unique_labels = sorted( sorted(list( ordered_unique_labels)), key = lambda x: int( re.search( "^[0-9]*", x).group() )  )
window = 2
for i in range( len( ordered_unique_labels) // window ):
    print( ordered_unique_labels[i*window:(i+1)*window])

print("\nPose")
ordered_unique_labels = set()
for value in df["Pose"].values:
    ordered_unique_labels.add(str(value))
print(ordered_unique_labels)
ordered_unique_labels = sorted( list( ordered_unique_labels) )
# for i in range( len( ordered_unique_labels) // window ):
#     print( ordered_unique_labels[i*window:(i+1)*window])

Uploaded Name
['1 - A71EV2A-x0911/A/147/1', '2 - A71EV2A-x3977/A/202/1']
['3 - A71EV2A-x0541/A/147/1', '4 - A71EV2A-x0525/A/246/1']
['5 - A71EV2A-x3181/A/202/1', '6 - A71EV2A-x0486/A/147/1']
['7 - A71EV2A-x0488/A/147/1', '8 - A71EV2A-x0517/A/147/1']
['9 - A71EV2A-x0432/A/147/1', '10 - A71EV2A-x0900/A/147/1']
['11 - A71EV2A-x0379/A/147/1', '12 - A71EV2A-x0396/A/147/1']
['13 - A71EV2A-x0412/A/147/1', '14 - A71EV2A-x0554/A/147/1']
['15 - A71EV2A-x1068/A/246/1', '16 - A71EV2A-x1068/A/302/1']
['17 - A71EV2A-x1081/A/201/1', '18 - A71EV2A-x7475/A/201/6']

Short Tag
['1 - A0911/A/147/1', '2 - A3977/A/202/1']
['3 - A0541/A/147/1', '4 - A0525/A/246/1']
['5 - A3181/A/202/1', '6 - A0486/A/147/1']
['7 - A0488/A/147/1', '8 - A0517/A/147/1']
['9 - A0432/A/147/1', '10 - A0900/A/147/1']
['11 - A0379/A/147/1', '12 - A0396/A/147/1']
['13 - A0412/A/147/1', '14 - A0554/A/147/1']
['15 - A1068/A/246/1', '16 - A1068/A/302/1']
['17 - A1081/A/201/1', '18 - A7475/A/201/6']

 Alias
['1 - Active Site', '2 - A3977/A/202/1']
['3 - A0541/A/147/1', '4 - A0525/A/246/1']
['5 - A3181/A/202/1', '6 - A0486/A/147/1']
['7 - A0488/A/147/1', '8 - A0517/A/147/1']
['9 - A0432/A/147/1', '10 - A0900/A/147/1']
['11 - A0379/A/147/1', '12 - A0396/A/147/1']
['13 - A0412/A/147/1', '14 - A0554/A/147/1']
['15 - A1068/A/246/1', '16 - A1068/A/302/1']
['17 - A1081/A/201/1', '18 - A7475/A/201/6']

Pose
{'A5687a', 'A3968a', 'A4563a', 'A4351a', 'A5394a', 'A4922a', 'A3550a', 'A4316a', 'A4974a', 'A3177a', 'A5247a', 'A3483a', 'A5475a', 'A4874a', 'A0278a', 'A2448a', 'A1145b', 'A0375c', 'A0446a', 'A3435a', 'A3066a', 'A4341a', 'A4028a', 'A3392a', 'A3581a', 'A5288a', 'A4715a', 'A4894a', 'A4675a', 'A4496a', 'A3324a', 'A0379a', 'A3548a', 'A4752a', 'A0515a', 'A3379a', 'A5258a', 'A5836a', 'A4418a', 'A5289a', 'A5584a', 'A7333a', 'A0554a', 'A0437a', 'A3410a', 'A5182a', 'A4372a', 'A6838a', 'A4877a', 'A4596a', 'A4421a', 'A3371a', 'A0188a', 'A4706a', 'A3306a', 'A4541a', 'A1068a', 'A4674a', 'A2458a', 'A4489a', 'A4840a', 'A0571a', 'A4239a', 'A5015a', 'A0269a', 'A0831a', 'A0922a', 'A3229a', 'A3436a', 'A4748a', 'A5249a', 'A4333a', 'A0853a', 'A5222a', 'A4684a', 'A3175a', 'A0514a', 'A3989a', 'A3963a', 'A1109a', 'A4949a', 'A0207a', 'A3616a', 'A0863a', 'A3194a', 'A4472a', 'A3938a', 'A0229a', 'A0469a', 'A4526a', 'A4644a', 'A4320a', 'A2972a', 'A3178a', 'A4420a', 'A4519a', 'A1209a', 'A4554a', 'A2339a', 'A0395a', 'A5393a', 'A3186a', 'A4575a', 'A3634a', 'A5016a', 'A5081a', 'A4429a', 'A3234a', 'A4954a', 'A3201a', 'A7491a', 'A4035a', 'A3618a', 'A3550b', 'A4712a', 'A4806a', 'A0515b', 'A1084a', 'A0497a', 'A4303a', 'A0152a', 'A0309a', 'A4721a', 'A4873a', 'A3890a', 'A0351c', 'A2513a', 'A4689a', 'A4708a', 'A4490a', 'A5598a', 'A3564a', 'A3568a', 'A3993a', 'A4321a', 'A3944a', 'A4826a', 'A4940a', 'A3210a', 'A5213a', 'A4537a', 'A3218a', 'A4305a', 'A3286a', 'A4514a', 'A7038a', 'A1128a', 'A3054a', 'A7147a', 'A4791a', 'A4882a', 'A4838a', 'A4707a', 'A3207a', 'A4451a', 'A5090a', 'A3621a', 'A0501a', 'A4694a', 'A0514b', 'A4538a', 'A1148a', 'A1775a', 'A3908a', 'A0541a', 'A4546a', 'A4020a', 'A4406a', 'A4967a', 'A3557a', 'A4829a', 'A5366a', 'A4670a', 'A3480a', 'A4724a', 'A2293a', 'A3279a', 'A4416a', 'A4846a', 'A4274a', 'A5082a', 'A3937a', 'A4390a', 'A3956a', 'A5330a', 'A5594a', 'A4309a', 'A2304a', 'A4824a', 'A0554b', 'A4673a', 'A4388a', 'A5104a', 'A0359a', 'A0719a', 'A4334a', 'A5073a', 'A0517a', 'A4703a', 'A5599a', 'A5879a', 'A0305a', 'A3901a', 'A5539a', 'A0717a', 'A4992a', 'A4559a', 'A4423a', 'A3869a', 'A4464a', 'A7175a', 'A3665a', 'A4347a', 'A0354a', 'A3223a', 'A3193a', 'A6738a', 'A7011a', 'A4880a', 'A0387a', 'A4342a', 'A3264a', 'A4381a', 'A4283a', 'A5022a', 'A4456a', 'A4979a', 'A0911a', 'A3975a', 'A4449a', 'A3181b', 'A1255a', 'A4254a', 'A4669a', 'A4739a', 'A1068c', 'A4292a', 'A4343a', 'A4827a', 'A0525a', 'A5039a', 'A4308a', 'A4845a', 'A4727a', 'A0351a', 'A4207a', 'A4315a', 'A3986a', 'A4710a', 'A4586a', 'A5449a', 'A4336a', 'A4736a', 'A4494a', 'A0450a', 'A0443a', 'A4402a', 'A4311a', 'A4346a', 'A4998a', 'A3181a', 'A3849a', 'A4516a', 'A0586a', 'A1293a', 'A4745a', 'A4350a', 'A4322a', 'A0152b', 'A1778a', 'A4544a', 'A3509a', 'A3510a', 'A4986a', 'A4319a', 'A7259a', 'A4947a', 'A3305a', 'A5283a', 'A1140a', 'A0202b', 'A0228a', 'A5262a', 'A4847a', 'A4461a', 'A4836a', 'A4903a', 'A0310a', 'A1105a', 'A3992a', 'A5151a', 'A4746a', 'A4306a', 'A5381a', 'A4777a', 'A4650a', 'A0202a', 'A5339a', 'A4753a', 'A5370a', 'A4380a', 'A4467a', 'A4298a', 'A3868a', 'A0451a', 'A1779a', 'A0365a', 'A5424a', 'A4855a', 'A3940a', 'A5388a', 'A3694a', 'A0341a', 'A6832a', 'A3403a', 'A1346a', 'A5091a', 'A7515a', 'A4331a', 'A0194a', 'A4344a', 'A4524a', 'A3571a', 'A5460a', 'A5666a', 'A3222a', 'A3606a', 'A5402a', 'A3593a', 'A5171a', 'A1776a', 'A3575a', 'A7459a', 'A5389a', 'A7132a', 'A4304a', 'A0487a', 'A4260a', 'A4914a', 'A5359a', 'A3954a', 'A0416a', 'A5383a', 'A3977b', 'A4509a', 'A4943a', 'A5427a', 'A0608a', 'A4290a', 'A3176a', 'A0528b', 'A0836a', 'A3417a', 'A0488a', 'A0812a', 'A4031a', 'A5351a', 'A5268a', 'A3189a', 'A3936a', 'A4583a', 'A5203a', 'A5317a', 'A5221a', 'A5425a', 'A0333a', 'A4872a', 'A5604a', 'A3977a', 'A3982a', 'A5177a', 'A4295a', 'A3450a', 'A3489a', 'A5512a', 'A4214a', 'A3883a', 'A4926a', 'A4977a', 'A3585a', 'A5065a', 'A0278b', 'A0332a', 'A0566a', 'A0528a', 'A4812a', 'A5255a', 'A4547a', 'A4774a', 'A4963a', 'A4895a', 'A4959a', 'A5106a', 'A4403a', 'A7475a', 'A5200a', 'A0875b', 'A4528a', 'A4596b', 'A7501a', 'A0237a', 'A0900a', 'A5079a', 'A0739a', 'A3895a', 'A4928a', 'A4899a', 'A4202a', 'A1445a', 'A4798a', 'A0556a', 'A4695a', 'A1080a', 'A3522a', 'A3485a', 'A7461a', 'A4203a', 'A4570a', 'A3685a', 'A1180a', 'A4313a', 'A5212a', 'A3612a', 'A0540a', 'A3939a', 'A4324a', 'A4237a', 'A4386a', 'A0351b', 'A4856a', 'A4784a', 'A4018a', 'A0526a', 'A3419a', 'A4611a', 'A3280a', 'A1146a', 'A4654a', 'A4317a', 'A4209a', 'A4445a', 'A5509a', 'A1292a', 'A0396a', 'A1081a', 'A2454a', 'A4908a', 'A3587a', 'A1169a', 'A3884a', 'A4431a', 'A4980a', 'A4794a', 'A4374a', 'A0428a', 'A3191a', 'A4447a', 'A1068b', 'A4310a', 'A1081b', 'A3623a', 'A4843a', 'A4935a', 'A4032a', 'A4571a', 'A3546a', 'A3579a', 'A5036a', 'A5210a', 'A4735a', 'A4365a', 'A7510a', 'A4415a', 'A3225a', 'A4463a', 'A7465a', 'A4809a', 'A4426a', 'A4291a', 'A5608a', 'A4742a', 'A2629a', 'A3188a', 'A4885a', 'A3488a', 'A4540a', 'A4994a', 'A4476a', 'A5488a', 'A5131a', 'A3920a', 'A0875a', 'A4771a', 'A0239a', 'A2846a', 'A4373a', 'A3990a', 'A3663a', 'A5466a', 'A7533a', 'A4017a', 'A5052a', 'A3556a', 'A0732a', 'A5721a', 'A5884a', 'A4580a', 'A5544a', 'A4701a', 'A3914a', 'A4751a', 'A0486a', 'A2290a', 'A4839a', 'A3706a', 'A0926a', 'A2351a', 'A1145a', 'A4883a', 'A4921a', 'A3521a', 'A0473a', 'A4606a', 'A4934a', 'A1148b', 'A5231a', 'A4368a', 'A5277a', 'A5150a', 'A4711a', 'A5525a', 'A4029a', 'A0719b', 'A3221a', 'A3408a', 'A3897a', 'A4778a', 'A7105a', 'A1019a', 'A4510a', 'A3208a', 'A0375a', 'A4312a', 'A4918a', 'A0691a', 'A3942a', 'A4409a', 'nan', 'A0432a', 'A0229b', 'A3867a', 'A4012a', 'A3858a', 'A4608a', 'A5219a', 'A0412a', 'A0884a', 'A4786a'}

In [95]:
count = 0

In [96]:
conf_of_int = ['1 - Active Site'] #  ['7a - A71EV2A-x0202/A/201', '7b - A71EV2A-x0488/A/147','7c - A71EV2A-x1081/A/147', '7d - A71EV2A-x1084/A/147']

print( df["Code"][ (df["CanonSites alias"] == conf_of_int[count]) ].to_list() )
count +=1

['A0450a', 'A0451a', 'A0473a', 'A0487a', 'A0501a', 'A0501b', 'A0514a', 'A0515a', 'A0526a', 'A0528a', 'A0554a', 'A0556a', 'A0566a', 'A0310a', 'A0207a', 'A0237a', 'A0351a', 'A0365a', 'A0375a', 'A0375b', 'A0387a', 'A0416a', 'A0437a', 'A0443a', 'A0446a', 'A0719a', 'A0732a', 'A0739a', 'A0812a', 'A0836a', 'A0836b', 'A0853a', 'A0875a', 'A0884a', 'A0911a', 'A0926a', 'A1019a', 'A1068a', 'A1080a', 'A1140a', 'A1148a', 'A1169a', 'A1180a', 'A1180b', 'A1209a', 'A1255a', 'A1292a', 'A1346a', 'A1445a', 'A1445b', 'A1775a', 'A1776a', 'A1778a', 'A1779a', 'A2290a', 'A2293a', 'A2304a', 'A2339a', 'A2351a', 'A2454a', 'A2513a', 'A2629a', 'A2846a', 'A2972a', 'A3054a', 'A3066a', 'A3175a', 'A3176a', 'A3177a', 'A3178a', 'A3181a', 'A3186a', 'A3188a', 'A3189a', 'A3191a', 'A3193a', 'A3194a', 'A3201a', 'A3207a', 'A3208a', 'A3210a', 'A3218a', 'A3221a', 'A3222a', 'A3223a', 'A3225a', 'A3229a', 'A3234a', 'A3264a', 'A3279a', 'A3280a', 'A3286a', 'A3305a', 'A3306a', 'A3324a', 'A3579a', 'A3581a', 'A3585a', 'A3587a', 'A3371a', 'A3379a', 'A3392a', 'A3403a', 'A3408a', 'A3410a', 'A3417a', 'A3419a', 'A3435a', 'A3436a', 'A3450a', 'A3480a', 'A3483a', 'A3485a', 'A3488a', 'A3489a', 'A3509a', 'A3509b', 'A3510a', 'A3593a', 'A3606a', 'A3612a', 'A3616a', 'A3616b', 'A3618a', 'A3621a', 'A3623a', 'A3634a', 'A3663a', 'A3665a', 'A3685a', 'A3694a', 'A3694b', 'A3706a', 'A3706b', 'A3521a', 'A3521b', 'A3522a', 'A3546a', 'A3548a', 'A3550a', 'A3556a', 'A3557a', 'A3557b', 'A3564a', 'A3568a', 'A3571a', 'A3571b', 'A3575a', 'A3849a', 'A3858a', 'A3858b', 'A3867a', 'A3868a', 'A3869a', 'A3883a', 'A3884a', 'A3884b', 'A3890a', 'A3895a', 'A3897a', 'A3901a', 'A3908a', 'A3914a', 'A3920a', 'A3936a', 'A3937a', 'A3938a', 'A3939a', 'A3940a', 'A3942a', 'A3944a', 'A3954a', 'A3956a', 'A3963a', 'A3963b', 'A3968a', 'A3975a', 'A3977a', 'A3982a', 'A3986a', 'A3986b', 'A3989a', 'A3990a', 'A3992a', 'A3992b', 'A3993a', 'A3993b', 'A4012a', 'A4012b', 'A4017a', 'A4017b', 'A4018a', 'A4018b', 'A4020a', 'A4020b', 'A4028a', 'A4029a', 'A4031a', 'A4031b', 'A4032a', 'A4032b', 'A4035a', 'A4035b', 'A4202a', 'A4202b', 'A4290a', 'A4291a', 'A4292a', 'A4295a', 'A4298a', 'A4303a', 'A4303b', 'A4304a', 'A4305a', 'A4306a', 'A4308a', 'A4309a', 'A4309b', 'A4310a', 'A4310b', 'A4311a', 'A4312a', 'A4313a', 'A4315a', 'A4316a', 'A4317a', 'A4319a', 'A4320a', 'A4321a', 'A4321b', 'A4322a', 'A4324a', 'A4331a', 'A4331b', 'A4333a', 'A4334a', 'A4334b', 'A4336a', 'A4341a', 'A4342a', 'A4343a', 'A4343b', 'A4344a', 'A4346a', 'A4347a', 'A4350a', 'A4351a', 'A4365a', 'A4365b', 'A4368a', 'A4372a', 'A4373a', 'A4374a', 'A4374b', 'A4380a', 'A4381a', 'A4203a', 'A4207a', 'A4207b', 'A4209a', 'A4214a', 'A4214b', 'A4237a', 'A4237b', 'A4239a', 'A4254a', 'A4260a', 'A4274a', 'A4274b', 'A4283a', 'A4283b', 'A4386a', 'A4388a', 'A4390a', 'A4402a', 'A4403a', 'A4406a', 'A4409a', 'A4415a', 'A4416a', 'A4418a', 'A4420a', 'A4421a', 'A4423a', 'A4429a', 'A4431a', 'A4445a', 'A4445b', 'A4447a', 'A4447b', 'A4449a', 'A4449b', 'A4451a', 'A4451b', 'A4456a', 'A4456b', 'A4461a', 'A4463a', 'A4464a', 'A4476a', 'A4489a', 'A4489b', 'A4490a', 'A4494a', 'A4496a', 'A4509a', 'A4510a', 'A4514a', 'A4519a', 'A4519b', 'A4524a', 'A4526a', 'A4528a', 'A4537a', 'A4538a', 'A4540a', 'A4541a', 'A4541b', 'A4544a', 'A4546a', 'A4547a', 'A4554a', 'A4559a', 'A4559b', 'A4563a', 'A4570a', 'A4571a', 'A4575a', 'A4580a', 'A4580b', 'A4583a', 'A4583b', 'A4586a', 'A4596a', 'A4596c', 'A4606a', 'A4606b', 'A4608a', 'A4611a', 'A4611b', 'A4644a', 'A4644b', 'A4650a', 'A4654a', 'A4669a', 'A4669b', 'A4673a', 'A4673b', 'A4674a', 'A4674b', 'A4684a', 'A4689a', 'A4694a', 'A4695a', 'A4701a', 'A4703a', 'A4706a', 'A4707a', 'A4708a', 'A4710a', 'A4711a', 'A4712a', 'A4715a', 'A4721a', 'A4724a', 'A4727a', 'A4735a', 'A4736a', 'A4739a', 'A4742a', 'A4742b', 'A4745a', 'A4746a', 'A4748a', 'A4751a', 'A4752a', 'A4753a', 'A4771a', 'A4777a', 'A4778a', 'A4786a', 'A4791a', 'A4794a', 'A4798a', 'A4806a', 'A4806b', 'A4809a', 'A4812a', 'A4824a', 'A4824b', 'A4826a', 'A4826b', 'A4827a', 'A4827b', 'A4829a', 'A4829b', 'A4836a', 'A4838a', 'A4839a', 'A4840a', 'A4846a', 'A4847a', 'A4855a', 'A4856a', 'A4873a', 'A4873b', 'A4874a', 'A4874b', 'A4877a', 'A4877b', 'A4880a', 'A4880b', 'A4882a', 'A4882b', 'A4883a', 'A4883b', 'A4885a', 'A4885b', 'A4894a', 'A4895a', 'A4895b', 'A4899a', 'A4899b', 'A4903a', 'A4903b', 'A4908a', 'A4918a', 'A4921a', 'A4922a', 'A4928a', 'A4934a', 'A4963a', 'A4963b', 'A4967a', 'A4967b', 'A4967c', 'A4974a', 'A4977a', 'A4977b', 'A4979a', 'A4979b', 'A4980a', 'A4986a', 'A4986b', 'A4940a', 'A4943a', 'A4943b', 'A4947a', 'A4949a', 'A4954a', 'A4959a', 'A4959b', 'A5016a', 'A5022a', 'A5022b', 'A5073a', 'A4845a', 'A4914a', 'A4992a', 'A5036a', 'A5036b', 'A5039a', 'A5039b', 'A5052a', 'A5079a', 'A5079b', 'A5081a', 'A5081b', 'A5082a', 'A5082b', 'A5090a', 'A5106a', 'A5151a', 'A5171a', 'A5171b', 'A5203a', 'A5203b', 'A5210a', 'A5210b', 'A5247a', 'A5247b', 'A5289a', 'A5289b', 'A5339a', 'A5339b', 'A5366a', 'A5366b', 'A4426a', 'A4467a', 'A4472a', 'A4516a', 'A4670a', 'A4675a', 'A4774a', 'A4784a', 'A4843a', 'A4872a', 'A4926a', 'A4935a', 'A4994a', 'A4998a', 'A5015a', 'A5015b', 'A5065a', 'A5091a', 'A5104a', 'A5150a', 'A5177a', 'A5182a', 'A5200a', 'A5212a', 'A5213a', 'A5213b', 'A5219a', 'A5219b', 'A5221a', 'A5222a', 'A5231a', 'A5249a', 'A5255a', 'A5258a', 'A5262a', 'A5262b', 'A5268a', 'A5277a', 'A5283a', 'A5283b', 'A5288a', 'A5288b', 'A5317a', 'A5359a', 'A5359b', 'A5131a', 'A5509a', 'A5525a', 'A5525b', 'A5544a', 'A5666a', 'A5383a', 'A5388a', 'A5389a', 'A5393a', 'A5394a', 'A5394b', 'A5402a', 'A5424a', 'A5424b', 'A5425a', 'A5425b', 'A5427a', 'A5449a', 'A5449b', 'A5460a', 'A5466a', 'A5475a', 'A5475b', 'A5488a', 'A5512a', 'A5512b', 'A5539a', 'A5539b', 'A5584a', 'A5584b', 'A5594a', 'A5594b', 'A5598a', 'A5598b', 'A5599a', 'A5599b', 'A5604a', 'A5608a', 'A5608b', 'A5330a', 'A5330b', 'A5351a', 'A5370a', 'A5370b', 'A5381a', 'A5381b', 'A5687a', 'A5721a', 'A5721b', 'A5836a', 'A5879a', 'A5879b', 'A5884a', 'A6738a', 'A6832a', 'A6838a', 'A7011a', 'A7014a', 'A7038a', 'A7105a', 'A7132a', 'A7147a', 'A7175a', 'A7259a', 'A7333a', 'A7459a', 'A7461a', 'A7465a', 'A7465b', 'A7515a']

### <ins> Get Overall Simple Statistics </ins>

In [107]:
print( "Total Number of Datasets-subsets pair: {}".format( len( df ) )  )
print( "Number of Unique Datasets: {}".format( df["Code"].apply( lambda x: x[:-1]  ).nunique() )  )
print( "Number of Datsets with Ligands Bound in Multiple Sites: {}".format( 
df["Code"].str[:-1][ df["Code"].str[:-1].isin(  df["Code"].str[:-1].value_counts()[ df["Code"].str[:-1].value_counts() > 1  ].index ) ].nunique() )  ) 
print( "Number of Datsets with Ligands Bound in a Single Site: {}".format( 
df["Code"].str[:-1][ df["Code"].str[:-1].isin(  df["Code"].str[:-1].value_counts()[ df["Code"].str[:-1].value_counts() == 1  ].index ) ].nunique() )  )

Total Number of Datasets-subsets pair: 686
Number of Unique Datasets: 536
Number of Datsets with Ligands Bound in Multiple Sites: 145
Number of Datsets with Ligands Bound in a Single Site: 391

### <ins> Look at Piperidine Series </ins>

#### Look at Piperidine Series Localization in Active Site

In [112]:
# Look at Piperidine series Location

pip_filter = df["[Series] Piperidine series"] == True
active_site = ['[Other] S1 site', '[Other] S2 site', '[Other] S3 site', '[Other] S4 site', '[Other] S5 site', "[Other] S1' site"]
active_site_filter = ( (df["[Other] S1 site"] == True) |
                (df["[Other] S2 site"] == True) |
                (df["[Other] S3 site"] == True) |
                (df["[Other] S4 site"] == True) |
                (df["[Other] S5 site"] == True) |
                (df["[Other] S1' site"] == True) 
              )
window_size = 10
idx = 0

In [ ]:
display(df[["Code", *active_site]][filter][ idx*window_size : (idx+1)*window_size ] )
idx += 1

,Code,[Other] S1 site,[Other] S2 site,[Other] S3 site,[Other] S4 site,[Other] S5 site,[Other] S1' site
239,A3940a,True,True,False,False,False,False
240,A3942a,True,True,False,False,False,False
241,A3944a,True,True,False,False,False,False
242,A3954a,True,True,False,False,False,False
244,A3963a,True,True,False,False,False,False
245,A3963b,True,True,False,False,False,False
246,A3968a,True,True,False,False,False,False
247,A3975a,True,True,False,False,False,False
250,A3982a,True,True,False,False,False,False
251,A3986a,True,True,True,False,False,False

#### Piperidine Series Overall Statistics

In [125]:
piperidine_df = df[pip_filter].copy()
pipedirine_codes = df[ "Code"][  active_site_filter & pip_filter  ]#.values.tolist()# (df["[Other] Active site fragment"] == True) &

print( "Total Number of Piperidine Datasets: {}".format( len( piperidine_df ) )  )              
print( "Number of Unique Piperidine Datasets: {}".format( piperidine_df["Code"].apply( lambda x: x[:-1]  ).nunique() )  )
print( "Number of Unique Piperidine Datsets with Ligands Bound in Multiple Sites: {}".format( 
piperidine_df["Code"].str[:-1][ piperidine_df["Code"].str[:-1].isin(  piperidine_df["Code"].str[:-1].value_counts()[ piperidine_df["Code"].str[:-1].value_counts() > 1  ].index ) ].nunique() )  ) 
print( "Number of Unique Piperidine Datsets with Ligands Bound in a Single Site: {}".format( 
piperidine_df["Code"].str[:-1][ piperidine_df["Code"].str[:-1].isin(  piperidine_df["Code"].str[:-1].value_counts()[ piperidine_df["Code"].str[:-1].value_counts() == 1  ].index ) ].nunique() )  ) 

print("\nActive Site")
print( f"Number of Piperidine compounds in Active Site: {len(pipedirine_codes)}" )     
print( f"Number of Unique Piperidine compounds in Active Site: {pipedirine_codes.apply( lambda x: x[:-1]  ).nunique()}" )

Total Number of Piperidine Datasets: 454
Number of Unique Piperidine Datasets: 347
Number of Unique Piperidine Datsets with Ligands Bound in Multiple Sites: 105
Number of Unique Piperidine Datsets with Ligands Bound in a Single Site: 242

Active Site
Number of Piperidine compounds in Active Site: 454
Number of Unique Piperidine compounds in Active Site: 347

### <ins> Fragment Screen Series </ins>

#### Overall Statistics

In [137]:
# Get All Types of Fragment Codes

active_site = ( (df["[Other] S1 site"] == True) |
                (df["[Other] S2 site"] == True) |
                (df["[Other] S3 site"] == True) |
                (df["[Other] S4 site"] == True) |
                (df["[Other] S5 site"] == True) |
                (df["[Other] S1' site"] == True) 
              )
allFragScreen_codes = df[ "Code"][ df["[Other] Fragment Screen"]==True ]

fragScreen_codes = df[ "Code"][ active_site & 
                        (df["[Other] Fragment Screen"]==True)  ]


pipedirineStartFrag_code = df[ "Code"][ (df["[Series] Piperidine series"] == True) &
                               (df["[Other] Fragment Screen"]==True)  ].values.tolist()

nonactivesite_codes = df[ "Code"][ ~(active_site) & 
                        (df["[Other] Sun-roof open"]==False)  ]

print( f"Number of All Fragalysis Fragment Screen compounds: {len(allFragScreen_codes)}" )
print( f"Number of Unique Fragalysis Fragment Screen compounds: { allFragScreen_codes.apply( lambda x: x[:-1]  ).nunique() }\n" )
print( f"Number of Fragment Screen compounds in Active Site: {len(fragScreen_codes)}" )
print( f"Number of Unique Fragment Screen compounds in Active Site: { fragScreen_codes.apply( lambda x: x[:-1]  ).nunique() }\n" )

print( f"Inital Fragments for Piperidine series: {(pipedirineStartFrag_code)}\n" )
print( f"Number of Non-Active Site compounds: {len(nonactivesite_codes)}" )
print( f"Number of Unique Non-Active Site compounds: { nonactivesite_codes.apply( lambda x: x[:-1]  ).nunique() }" )

Number of All Fragalysis Fragment Screen compounds: 105
Number of Unique Fragalysis Fragment Screen compounds: 87

Number of Fragment Screen compounds in Active Site: 42
Number of Unique Fragment Screen compounds in Active Site: 41

Inital Fragments for Piperidine series: ['A0926a']

Number of Non-Active Site compounds: 99
Number of Unique Non-Active Site compounds: 79

### <ins> Non Active Site Ligands </ins>

- #### Option 1: Filter By Labels

In [138]:
nonactivesite_filter =  ( ~(active_site) & (df["[Other] Sun-roof open"]==False) )
nonactivesite_df = df[ nonactivesite_filter ].copy()
print( "Total Number of Non-Active Site Datasets: {}".format( len( nonactivesite_df ) )  )
print( "Number of Unique Non-Active Site Datasets: {}".format( nonactivesite_df["Code"].apply( lambda x: x[:-1  ]  ).nunique() )  )                                                             
print( "Number of Unique Non-Active Site Datsets with Ligands Bound in Multiple Sites: {}".format( 
nonactivesite_df["Code"].str[:-1][ nonactivesite_df["Code"].str[:-1].isin(  nonactivesite_df["Code"].str[:-1].value_counts()[ nonactivesite_df["Code"].str[:-1].value_counts() > 1  ].index ) ].nunique() )  ) 
print( "Number of Unique Non-Active Site Datsets with Ligands Bound in a Single Site: {}".format( 
nonactivesite_df["Code"].str[:-1][ nonactivesite_df["Code"].str[:-1].isin(  nonactivesite_df["Code"].str[:-1].value_counts()[ nonactivesite_df["Code"].str[:-1].value_counts() == 1  ].index ) ].nunique() )  )

Total Number of Non-Active Site Datasets: 99
Number of Unique Non-Active Site Datasets: 79
Number of Unique Non-Active Site Datsets with Ligands Bound in Multiple Sites: 19
Number of Unique Non-Active Site Datsets with Ligands Bound in a Single Site: 60

- #### Option 2: Filter By Distance from Active Site

### <ins> Extract Piperidine, Fragment, Nonactive, Apo subset </ins>

Locations:
-  fragalysis/02-chemofint (chemicals of Interest)
    - /fragscreen/
    - /piperid/
    - /nonactive/
    - /fragscreen_lig.pdb
    - /piperid_lig.pdb
    - /startchem_lig.pdb
    - /ground_prot.pdb

In [ ]:
# Set Directories
rootdir = Path( "./../../../../data/ev2a/fragalysis/02-chemofint" ).resolve()
rootdir.mkdir( exist_ok=True, parents=True )

fragdir = rootdir / "fragscreen"
fragdir.mkdir( exist_ok=True, parents=True )

piperidir = rootdir / "piperid"
piperidir.mkdir( exist_ok=True, parents=True )

nonactivedir = rootdir / "nonactivesite"
nonactivedir.mkdir( exist_ok=True, parents=True )

#### Create and Populate `fragscreen`, `piperid`, and `nonactive` folders

In [ ]:
# Copy Key Folders and files into new directories
from shutil import copy2

srcRootDir = Path( "./../../../../data/ev2a/fragalysis/01-concatDir/aligned_files" ).resolve()

def cp_codes( srcDir, destDir, codes ):
    for code in codes:
        dest = destDir / code
        dest.mkdir( exist_ok=True, parents=True )
        src = srcDir / code
        if not src.exists():
            print( f"Source directory not found: {src}, skipping..." )
            continue
        for srcFile in src.iterdir():
            filename = srcFile.name
            dstFile =  dest / filename
            copy2( srcFile, dstFile)
    print( f"Copied {len(codes)} codes to {destDir}" )

# cp_codes( srcRootDir, fragdir, fragScreen_codes ) # Copy Fragments into New Folder
# cp_codes( srcRootDir, piperidir, pipedirine_codes ) # Copy Piperidines into New Folder
cp_codes( srcRootDir, nonactivedir, nonactivesite_codes ) # Copy Non-actives into New Folder

Copied 99 codes to /dls/data2temp01/alex/data/ev2a/fragalysis/02-chemofint/nonactivesite

### Merge Subset Ligand Files (`piperid_lig`, `fragscreen_lig`, `startchem_lig`)

In [ ]:
# Merge Ligands into single file for ease of use in PyMOL
from rdkit import Chem

def merge_sdf_files( input_files, output_file ):
    writer = Chem.SDWriter(output_file)
    for filename in input_files:
        try:
            supplier = Chem.SDMolSupplier(filename)
        except FileNotFoundError:
            print(f"File not found: {filename}")
            continue
        for mol in supplier:
            if mol is not None:
                writer.write(mol)
    writer.close()
    print(f"Successfully written merged file to: {output_file}")

# input_files = [ str(piperidir / code / f"{code}.sdf") for code in pipedirine_codes ]
# output_file = rootdir / 'piperidir_lig.sdf'
# merge_sdf_files( input_files, output_file )
# input_files = [ str(fragdir / code / f"{code}.sdf") for code in fragScreen_codes ]
# output_file = rootdir / 'fragscreen_lig.sdf'
# merge_sdf_files( input_files, output_file )

copy2( piperidir / "A0926a"/ "A0926a.sdf", rootdir / "startchem_lig.sdf" )

PosixPath('/dls/data2temp01/alex/data/ev2a/fragalysis/02-chemofint/startchem_lig.sdf')

### Merge all Apo Prots (`ground_prot`)

In [ ]:
import gemmi

merged_pdb = gemmi.Structure()
merged_pdb.name = "merged_nonactivesite"

for code in nonactivesite_codes:
    pdb_path = nonactivedir / code / f"{code}_apo-desolv.pdb"
    try:
        pdb_obj = gemmi.read_pdb( str(pdb_path))
    except Exception as e:
        print( f"Error reading PDB file {code}: {e}, skipping..." )
        continue
    pdb_model = pdb_obj[0]
    merged_pdb.add_model( pdb_model)
output_file = rootdir / 'ground_prot.pdb'
merged_pdb.write_pdb( str(output_file) )

Error reading PDB file A7459a: Problem in line 2547: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7465a: Problem in line 2573: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7465b: Problem in line 2581: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7475a: Problem in line 2642: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7475b: Problem in line 2604: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7491a: Problem in line 2617: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7491b: Problem in line 2573: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7501a: Problem in line 2588: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7501b: Problem in line 2558: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7510a: Problem in line 2541: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7510b: Problem in line 2519: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7515a: Problem in line 2536: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7533a: Problem in line 2547: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...
Error reading PDB file A7533b: Problem in line 2543: Duplicated ANISOU record or not directly after ATOM/HETATM., skipping...