## Rest of file types

In [1]:
#Initialize Notebook Environment
from pathlib import Path
import sys
sys.path.insert( 0, Path("../..").resolve().absolute().__str__() )

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from xaidar.filesUtils import loadPickle

xc_dataDir = Path( "../../../data/s3Sizes/xchem/filetypes" )
xc_dataStats = loadPickle( xc_dataDir / "stats_filetype_sizes.pkl" )
xc_dataStats_df = pd.DataFrame( xc_dataStats )

pd_dataDir = Path( "../../../data/s3Sizes/pandda/filetypes" )
pd_dataStats = loadPickle( pd_dataDir / "stats_filetype_sizes.pkl" )
pd_dataStats_df = pd.DataFrame( pd_dataStats )

print( "XChem Data Statistics:" )
display( xc_dataStats_df.head(2))
print( "Pandda Data Statistics:" )
display( pd_dataStats_df.head(2) )

XChem Data Statistics:

,File Type,Files Count,Median,Mean,Std,1stQrt,3rdQrt,QrtDeviation,Max,Min,Sum
0,.csv,492956,1860.0,13679.315385,3.242432e+05,1356.0,3357.0,1000.5,80906623,0,6743300595
1,.txt,3458488,10672.0,304168.266793,3.178951e+06,1380.0,25226.0,11923.0,487143107,0,1051962300685

Pandda Data Statistics:

,File Type,Files Count,Median,Mean,Std,1stQrt,3rdQrt,QrtDeviation,Max,Min,Sum
0,.csv,168,61908.0,239908.482143,489547.716090,23280.75,228948.0,102833.625,3606844,3,40304625
1,.log,608435,9143.0,20228.220240,22693.793181,738.00,39411.0,19336.500,309100,0,12307557182

## How many filetypes exist

In [ ]:
xc_lstFileTypes = list(xc_dataStats_df["File Type"].values)

xc_removedFileTypes = [ file for file in list(xc_lstFileTypes) if re.search( "^\\....[0-9][0-9][0-9]", file) ] 
xc_updatedFileTypes = [ file for file in list(xc_lstFileTypes) if not re.search( "^\\....[0-9][0-9][0-9]", file)]

xc_removedFileTypes.extend( [ file for file in xc_updatedFileTypes if  re.search( "^\\.[0-9][0-9][0-9][0-9]", file)] )# i.e. .21610_VDW_R
xc_updatedFileTypes = [ file for file in xc_updatedFileTypes if not re.search( "^\\.[0-9][0-9][0-9][0-9]", file)]  # i.e. .21610_VDW_R

xc_removedFileTypes.extend( [ file for file in xc_updatedFileTypes if  re.search( "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]", file)] )
xc_updatedFileTypes = [ file for file in xc_updatedFileTypes if not re.search( "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]", file)]  


xc_updatedFileTypes = sorted( xc_updatedFileTypes)
xc_removedFileTypes = sorted( xc_removedFileTypes)

print(f"Number of File types after removing odds ones: {len(xc_updatedFileTypes)}")
print(f"Number of Removed File types: {len(xc_removedFileTypes)}")

pd_lstFileTypes = list(pd_dataStats_df["File Type"].values)

pd_removedFileTypes = [ file for file in list(pd_lstFileTypes) if re.search( "^\\....[0-9][0-9][0-9]", file) ]
pd_updatedFileTypes = [ file for file in list(pd_lstFileTypes) if not re.search( "^\\....[0-9][0-9][0-9]", file)]

pd_removedFileTypes.extend( [ file for file in pd_updatedFileTypes if  re.search( "^\\.[0-9][0-9][0-9][0-9]", file)] )# i.e. .21610_VDW_R
pd_updatedFileTypes = [ file for file in pd_updatedFileTypes if not re.search( "^\\.[0-9][0-9][0-9][0-9]", file)]  # i.e. .21610_VDW_R

pd_removedFileTypes.extend( [ file for file in pd_updatedFileTypes if  re.search( "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]", file)] )
pd_updatedFileTypes = [ file for file in pd_updatedFileTypes if not re.search( "[0-9][0-9][0-9][0-9][0-9][0-9][0-9]", file)]

pd_updatedFileTypes = sorted( pd_updatedFileTypes)
pd_removedFileTypes = sorted( pd_removedFileTypes)

print(f"\nNumber of File types after removing odds ones: {len(pd_updatedFileTypes)}")
print(f"Number of Removed File types: {len(pd_removedFileTypes)}")